<a href="https://colab.research.google.com/github/Diyaash/Data-Structures/blob/main/NUMPY_FUNDAMENTALS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy

NumPy (Numerical Python) is a fundamental library in Python for numerical and scientific computing.
It provides support for arrays, matrices, and a wide range of mathematical functions to work efficiently with large datasets and perform various mathematical operations

# Creating NumPy Array

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr_2 = np.array({1,2,3,4,5})
print(type(arr), type(arr_2))

zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((5, 5))

print(zeros_arr)
print(ones_arr)
import random

arr = np.arange(0, 10, 2)  # Creates an array [0, 2, 4, 6, 8]
arr_2 = np.linspace(1, 10, 10)  # Creates an array [0.  , 0.25, 0.5 , 0.75, 1.  ]
print(arr, arr_2)

rand_arr = np.random.rand(4, 4)
print(rand_arr)

arr = np.array([1,2,3,4], ndmin=4)
print(arr)

#16 = 8*2, 2*8, 4*4, 16*1, 1*16

reshaped_array = rand_arr.reshape(2,8)
print(reshaped_array)
print(reshaped_array.shape)
print(reshaped_array.ndim)

print(reshaped_array.dtype)
print(type(reshaped_array))


arr = np.array([1,2,3,4], dtype='i')
print(arr.dtype)

#bits - fundamental unit -> 8 bit 1 bite -> KB, MB, GB, TB
#1024 bytes = 1kb

str_arr = np.array(['dogs','cats','horses'], dtype='S')  # to initalize with a specific datatype
str_arr

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 2 4 6 8] [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[0.29331198 0.09444711 0.065431   0.61056814]
 [0.96024871 0.47991728 0.77571111 0.72997042]
 [0.97131453 0.75971199 0.58468999 0.76241238]
 [0.60076872 0.5892324  0.28047825 0.37987164]]
[[[[1 2 3 4]]]]
[[0.29331198 0.09444711 0.065431   0.61056814 0.96024871 0.47991728
  0.77571111 0.72997042]
 [0.97131453 0.75971199 0.58468999 0.76241238 0.60076872 0.5892324
  0.28047825 0.37987164]]
(2, 8)
2
float64
<class 'numpy.ndarray'>
int32


array([b'dogs', b'cats', b'horses'], dtype='|S6')

In [ ]:
#help(np.array)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr[0,2])
arr[0,2] = 44
print(arr[0,2])

print(arr[0:2,0:2])

mask = arr > 5
even_slicing = (arr % 2 == 0)
#print(even_slicing)
sliced_array_with_bool = arr[even_slicing]
#print(sliced_array_with_bool)

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
#?a.shape


3
44


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

k = 5

print(arr1 ** 2)
print(arr1 * k)
print(arr1 * 77)
print(arr1 + arr2)
print(arr1 * arr2)

mean = np.mean(arr1)
std_dev = np.std(arr2)
print('mean:',mean,'std_dev:' ,std_dev)


print(arr2.max())
print(arr2.min())
print(arr2.sum())


[1 4 9]
[ 5 10 15]
[ 77 154 231]
[5 7 9]
[ 4 10 18]
mean: 2.0 std_dev: 0.816496580927726
6
4
15


# Pandas Dataframe

In [ ]:
import pandas as pd


data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df_from_dict = pd.DataFrame(data)

df_from_dict

Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
# Creating a DataFrame from a list of lists with custom column names
data_list = [['Alice', 25], ['Bob', 30], ['Charlie', 35]]
df_from_list = pd.DataFrame(data_list, columns=['Name', 'Age'])

df_from_list

Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
#help(pd.DataFrame)

In [ ]:

df_from_csv = pd.read_csv('/content/sample_data/california_housing_test.csv')
#df2_from_csv = pd.read_csv('/content/sample_data/mnist_train_small.csv')
df_from_csv.shape


(3000, 9)

In [ ]:
df_from_csv.info()
#df2_from_csv.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [ ]:
df_from_csv.describe()

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000   273.00000       2.544000   
50%        437.000000   1155.000000   409.50000       3.487150   
75%        636.000000   1742.750000   597.25000       4.656475   
max       5419.000000  11935.000000  4930.00000      15.000100   

       median_house_value  
count          3000.00000  
mean         205846.27500  
std          113119.68747  
min           22500.00000  
25%          121200.00000  
50%          177650.00000  
75%          263975.00000  
max          500001.00000

In [ ]:

df_from_csv.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0

In [ ]:
df_from_csv.tail(7)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2993    -117.91     33.60                37.0       2088.0           510.0   
2994    -117.93     33.86                35.0        931.0           181.0   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
2993       673.0       390.0         5.1048            500001.0  
2994       516.0       174.0         5.5867            182500.0  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0

In [ ]:
df_from_csv['population']

0       1537.0
1        809.0
2       1484.0
3         49.0
4        850.0
         ...  
2995    1258.0
2996    3496.0
2997     693.0
2998      46.0
2999     753.0
Name: population, Length: 3000, dtype: float64

In [ ]:
df_from_csv.population

0       1537.0
1        809.0
2       1484.0
3         49.0
4        850.0
         ...  
2995    1258.0
2996    3496.0
2997     693.0
2998      46.0
2999     753.0
Name: population, Length: 3000, dtype: float64

In [ ]:
df_2 = df_from_csv.iloc[: , 5:6 ]
df_2

pandas.core.frame.DataFrame

In [ ]:
df_from_csv.iloc[: , [5] ]

population
0         1537.0
1          809.0
2         1484.0
3           49.0
4          850.0
...          ...
2995      1258.0
2996      3496.0
2997       693.0
2998        46.0
2999       753.0

[3000 rows x 1 columns]

### From List to Tuples

In [ ]:
import numpy as np
import pandas as pd

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Convert NumPy array to pandas DataFrame
df = pd.DataFrame(arr, columns=['Column_Name'])

# Print the DataFrame
print(df)


   Column_Name
0            1
1            2
2            3
3            4
4            5


### Using Built-in Functions

### Creates a 3x3 array filled with zeros

In [ ]:
import numpy as np
import pandas as pd

# Create a NumPy array filled with zeros
zeros_arr = np.zeros((3, 3))

# Convert NumPy array to pandas DataFrame
df = pd.DataFrame(zeros_arr)

# Print the DataFrame
print(df)


     0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0


### Creates a 2x2 array filled with ones

In [ ]:
import numpy as np
import pandas as pd

# Create a NumPy array filled with ones
ones_arr = np.ones((2, 2))

# Convert NumPy array to pandas DataFrame
df = pd.DataFrame(ones_arr)

# Print the DataFrame
print(df)


     0    1
0  1.0  1.0
1  1.0  1.0


### np.arange() and np.linspace() are NumPy functions used to create arrays with a sequence of numbers.

### np.arange()

In [ ]:
import numpy as np

# Create array using arange
arr = np.arange(0, 10, 2)  # Creates an array [0, 2, 4, 6, 8]

# Print the array
print("Array from arange:")
print(arr)


Array from arange:
[0 2 4 6 8]


### np.linspace()

In [ ]:
import numpy as np

# Create array using linspace
lin_arr = np.linspace(0, 1, 5)  # Creates an array [0.  , 0.25, 0.5 , 0.75, 1.  ]

# Print the array
print("Array from linspace:")
print(lin_arr)


Array from linspace:
[0.   0.25 0.5  0.75 1.  ]


### Random Arrays - Random arrays are arrays whose elements are generated randomly.

### Creates a 3x3 array with random values between 0 and 1

In [ ]:
import numpy as np

# Create a 3x3 array with random values between 0 and 1
rand_arr = np.random.rand(3, 3)

# Print the random array
print(rand_arr)


[[0.57936543 0.53831709 0.14070349]
 [0.02399519 0.46628355 0.48844001]
 [0.71512733 0.02199874 0.36509733]]


### Using Dimension to generate N-dimensional arrays

In [ ]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the array
print(arr)

[[1 2 3 4]]


### The reshape() method in NumPy allows you to change the shape of an array

In [ ]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Reshape the array to a 2x2 shape
reshaped_arr = arr.reshape((2, 2))

# Print the reshaped array
print(reshaped_arr)


[[1 2]
 [3 4]]


###  You can check the type of the array object using the type() function in Python.

In [ ]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the type of the array object
print(type(arr))


<class 'numpy.ndarray'>


### You can use the shape attribute of a NumPy array to check its dimensions.

In [ ]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the shape of the array
print(arr.shape)


(1, 4)


### You can use the ndim attribute of a NumPy array to check its number of dimensions.

In [ ]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the number of dimensions of the array
print(arr.ndim)


2


### Data Types in NumPy

### Strings are sequences of characters, such as letters, numbers, symbols, or spaces, enclosed within single quotes (') or double quotes (").

In [ ]:
import numpy as np

# Create a NumPy array of strings
str_arr = np.array(['ABC', 'DEF'], dtype=np.str_)

# Print the array
print("String array:", str_arr)


String array: ['ABC' 'DEF']


### Integers are whole numbers, positive or negative, without any decimal point.

In [ ]:
import numpy as np

# Create a NumPy array of integers
int_arr = np.array([1, 2, 3], dtype=np.int64)

# Print the array
print("Integer array:", int_arr)


Integer array: [1 2 3]


### Floats (floating-point numbers) are numbers that have a decimal point or use exponential (scientific) notation. They can represent both integer and fractional parts of numbers.

In [ ]:
import numpy as np

# Create a NumPy array of floats
float_arr = np.array([5.98, 3.14], dtype=np.float64)

# Print the array
print("Float array:", float_arr)


Float array: [5.98 3.14]


### Booleans are a data type that represents one of two possible values: True or False.

In [ ]:
import numpy as np

# Create a NumPy array of booleans
bool_arr = np.array([True, False, True], dtype=np.bool_)

# Print the array
print("Boolean array:", bool_arr)


Boolean array: [ True False  True]


### Complex numbers consist of a real part and an imaginary part, where the imaginary part is represented by the letter j or J.

In [ ]:
import numpy as np

# Create a NumPy array of complex numbers
complex_arr = np.array([1.0 + 2.0j, 3.0 + 4.0j], dtype=np.complex128)

# Print the array
print("Complex array:", complex_arr)


Complex array: [1.+2.j 3.+4.j]


### Creating NumPy arrays with specific data types using the dtype parameter.

### Creating an array of integers without specifying the data type:

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)  # int32


int32


### Creating an array of strings with a specific data type ('S' for strings):

In [ ]:
arr = np.array(['dogs', 'cats', 'horses'], dtype='S')
print(arr.dtype)  # |S6


|S6


# Indexing and Slicing NumPy Arrays


### NumPy arrays can be accessed and sliced similar to Python lists, with the additional ability to index and slice in multiple dimensions for multi-dimensional arrays.


### Create a Numpy Array

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

### Accessing elements

In [ ]:
element = arr[0, 1]  # Accessing the element at the first row and second column
print("Element at first row and second column:", element)

Element at first row and second column: 2


### Slicing Rows

In [ ]:
slice_row = arr[1, :]  # Slicing the second row
print("Second row:", slice_row)

Second row: [4 5 6]


### Slicing Columns


In [ ]:
slice_column = arr[:, 2]  # Slicing the third column
print("Third column:", slice_column)

Third column: [3 6 9]


### Advanced indexing with boolean masking

In [ ]:
mask = arr > 5  # Creating a boolean mask for values greater than 5
filtered = arr[mask]  # Getting values greater than 5
print("Boolean mask for values greater than 5:\n", mask)
print("Values greater than 5:\n", filtered)

Boolean mask for values greater than 5:
 [[False False False]
 [False False  True]
 [ True  True  True]]
Values greater than 5:
 [6 7 8 9]


### Create the following rank 2 array with shape (3, 4)


In [ ]:
import numpy as np

# Given NumPy array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Print the array
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2; b is the following array of shape (2, 2):


In [ ]:
import numpy as np

# Given NumPy array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Slicing the array
b = a[:2, 1:3]

# Print the sliced array
print("Sliced array b:")
print(b)


Sliced array b:
[[2 3]
 [6 7]]


### A slice of an array is a view into the same data, so modifying it will modify the original array.


In [ ]:
import numpy as np

# Given NumPy array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Slicing the array
b = a[:2, 1:3]

# Print element of a
print("Element of a[0, 1]:", a[0, 1])   # Prints "2"

# Modify element of b
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]

# Print modified element of a
print("Modified element of a[0, 1]:", a[0, 1])   # Prints "77"


Element of a[0, 1]: 2
Modified element of a[0, 1]: 77


# Numpy Operations

### NumPy arrays support a wide range of operations, including arithmetic, statistical, and more. These operations are performed element-wise.


### Element-wise arithmetic operations - In element-wise operations, corresponding elements of the input structures are operated on together to produce an output structure of the same shape.


In [ ]:
import numpy as np

# Given NumPy arrays
arr1 = np.array([1, 2, 3])  # Define the first NumPy array
arr2 = np.array([4, 5, 6])  # Define the second NumPy array



### Element-wise Addition:It refers to the process of adding corresponding elements of two arrays, matrices, or vectors together to produce a new array, matrix, or vector of the same shape.

In [ ]:
addition = arr1 + arr2  # Perform element-wise addition
print("Element-wise addition:", addition)  # Print the result of addition


Element-wise addition: [5 7 9]


### Element-wise Subtraction:It is similar to element-wise addition, but instead of adding corresponding elements, it involves subtracting them.

In [ ]:
subtraction = arr1 - arr2  # Perform element-wise subtraction
print("Element-wise subtraction:", subtraction)  # Print the result of subtraction


Element-wise subtraction: [-3 -3 -3]


### Element-wise Multiplication: It is a mathematical operation in which corresponding elements of two arrays, matrices, or vectors are multiplied together to produce a new array, matrix, or vector of the same shape.

In [ ]:
multiplication = arr1 * arr2  # Perform element-wise multiplication
print("Element-wise multiplication:", multiplication)  # Print the result of multiplication


Element-wise multiplication: [ 4 10 18]


### Element-wise Division: It is a mathematical operation where corresponding elements of one array, matrix, or vector are divided by corresponding elements of another array, matrix, or vector, resulting in a new array, matrix, or vector of the same shape.

In [ ]:
division = arr1 / arr2  # Perform element-wise division
print("Element-wise division:", division)  # Print the result of division


Element-wise division: [0.25 0.4  0.5 ]


### Statistical operations


### Statistical operations refer to various mathematical procedures used to analyze, interpret, summarize, and draw conclusions from data.

In [ ]:
import numpy as np

# Given NumPy arrays
arr1 = np.array([1, 2, 3])  # Define the first NumPy array
arr2 = np.array([4, 5, 6])  # Define the second NumPy array

# Calculate mean and standard deviation
mean_arr1 = np.mean(arr1)  # Calculate the mean of arr1
std_dev_arr2 = np.std(arr2)  # Calculate the standard deviation of arr2

# Print results
print("Mean of arr1:", mean_arr1)  # Print the mean of arr1
print("Standard deviation of arr2:", std_dev_arr2)  # Print the standard deviation of arr2


Mean of arr1: 2.0
Standard deviation of arr2: 0.816496580927726


### Geometric Operations

### Exponentiation: Raises each element of the array to the power of Euler's number.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])  # Define the input array
result_exp = np.exp(arr1)   # Compute element-wise exponentiation
print("Exponentiation of arr1:", result_exp)


Exponentiation of arr1: [ 2.71828183  7.3890561  20.08553692]


### Square Root: Computes the square root of each element in the array.

In [ ]:
import numpy as np

arr1 = np.array([4, 9, 16])  # Define the input array
result_sqrt = np.sqrt(arr1)  # Compute element-wise square root
print("Square root of arr1:", result_sqrt)


Square root of arr1: [2. 3. 4.]


### Sine: Computes the sine of each element in the array treated as angles in radians.

In [ ]:
import numpy as np

arr1 = np.array([0, np.pi/2, np.pi])  # Define the input array (angles in radians)
result_sin = np.sin(arr1)             # Compute element-wise sine
print("Sine of arr1:", result_sin)


Sine of arr1: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


### Cosine: Computes the cosine of each element in the array treated as angles in radians.

In [ ]:
import numpy as np

arr1 = np.array([0, np.pi/2, np.pi])  # Define the input array (angles in radians)
result_cos = np.cos(arr1)             # Compute element-wise cosine
print("Cosine of arr1:", result_cos)


Cosine of arr1: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


### Natural Logarithm: Computes the natural logarithm (base e) of each element in the array.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])  # Define the input array
result_log = np.log(arr1)   # Compute element-wise natural logarithm
print("Natural logarithm of arr1:", result_log)


Natural logarithm of arr1: [0.         0.69314718 1.09861229]


### Aggregate Functions

### Sum: Computes the sum of all elements in the array.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # Define the input array

# Sum of all elements in the array
sum_result = arr1.sum()
print("Sum of arr1:", sum_result)

Sum of arr1: 15


### Minimum: Finds the minimum value among all elements in the array.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # Define the input array

# Minimum value among all elements in the array
min_result = arr1.min()
print("Minimum value in arr1:", min_result)

Minimum value in arr1: 1


### Maximum: Finds the maximum value among all elements in the array.

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])  # Define the input array

# Maximum value among all elements in the array
max_result = arr1.max()
print("Maximum value in arr1:", max_result)

Maximum value in arr1: 5


# Panda Series

### Pandas is a Python library for data manipulation and analysis, offering data structures like Series and DataFrame for handling structured data efficiently,

### creating a pandas series

In [ ]:
  import pandas as pd

# Creating a Series from a list
data = [10, 20, 30, 40, 50]
series_from_list = pd.Series(data)


In [ ]:
import pandas as pd
import numpy as np

# Creating a Series from a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])
series_from_numpy = pd.Series(numpy_array)


In [ ]:
import pandas as pd

# Creating a Series with custom index labels
data = [10, 20, 30, 40, 50]
custom_index = pd.Series(data, index=['A', 'B', 'C', 'D', 'E'])


### Accessing elements by position (zero-based index)

This operation retrieves an element from a pandas Series based on its position, which follows a zero-based index (the first element has index 0, the second has index 1, and so on).

In [ ]:
# Example:
element_at_position_2 = series_from_list[2]
print("Element at position 2:", element_at_position_2)


Element at position 2: 30


### Accessing elements by label

 - This operation retrieves an element from a pandas Series based on its label.
 - When you create a Series with custom index labels, you can access elements using these labels.

In [ ]:
# Example:
element_with_label_B = custom_index['B']
print("Element with label 'B':", element_with_label_B)


Element with label 'B': 20


### Slicing a series

Slicing allows you to select a subset of elements from a Series based on their positions.

In [ ]:
# Example:
slice_series = series_from_list[1:4]
print("Slice of series_from_list:", slice_series)


Slice of series_from_list: 1    20
2    30
3    40
dtype: int64


# Creating Pandas DataFrame

### Creating a DataFrame from a dictionary

In [ ]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]}
df_from_dict = pd.DataFrame(data)

# Print the DataFrame
print("DataFrame created from dictionary:")
print(df_from_dict)



DataFrame created from dictionary:
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


### Creating a DataFrame from a list of lists with custom column names


In [ ]:
import pandas as pd

# Creating a DataFrame from a list of lists with custom column names
data_list = [['Alice', 25], ['Bob', 30], ['Charlie', 35]]
df_from_list = pd.DataFrame(data_list, columns=['Name', 'Age'])

# Print the DataFrame
print("DataFrame created from list of lists with custom column names:")
print(df_from_list)


DataFrame created from list of lists with custom column names:
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


### Creating a DataFrame from a CSV file


In [ ]:
import pandas as pd

# Creating a DataFrame from a CSV file
df_from_csv = pd.read_csv('data.csv')

# Print the DataFrame
print("DataFrame created from CSV file:")
print(df_from_csv)


DataFrame created from CSV file:
    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..    

### Creating an empty DataFrame


In [ ]:
import pandas as pd

# Creating an empty DataFrame
empty_df = pd.DataFrame()

# Print the empty DataFrame
print("Empty DataFrame:")
print(empty_df)


Empty DataFrame:
Empty DataFrame
Columns: []
Index: []


# Indexing a Pandas DataFrame

### DataFrames allow for various methods of indexing, including selecting columns, filtering rows, and more.


### Selecting a single column


In [ ]:
# Selecting a single column
name_column = df_from_dict['Name']
print(name_column)


0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object


###  Selecting multiple columns


In [ ]:
# Selecting multiple columns
subset = df_from_dict[['Name', 'Age']]
print(subset)


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


### Filtering Rows based on a condition

In [ ]:
# Filtering rows based on a condition
young_people = df_from_dict[df_from_dict['Age'] < 30]
print(young_people)


    Name  Age
0  Alice   25


### Accessing a specific cell by row and column label


In [ ]:
# Accessing a specific cell by row and column label
cell_value = df_from_dict.at[0, 'Name']
print("Value at cell (row 0, column 'Name'):", cell_value)



Value at cell (row 0, column 'Name'): Alice


# Loading Data from files


### SQL Databases - You can connect to SQL databases and retrieve data using Pandas.


In [ ]:
from sqlalchemy import create_engine

In [ ]:
# Create a database connection
engine = create_engine('sqlite:///database.db')

In [ ]:
data_from_sql = pd.read_sql_query('SELECT * FROM tracks', engine)

In [ ]:
data_from_sql

TrackId                                               Name  AlbumId  \
0           1            For Those About To Rock (We Salute You)        1   
1           2                                  Balls to the Wall        2   
2           3                                    Fast As a Shark        3   
3           4                                  Restless and Wild        3   
4           5                               Princess of the Dawn        3   
...       ...                                                ...      ...   
3498     3499  Pini Di Roma (Pinien Von Rom) \ I Pini Della V...      343   
3499     3500  String Quartet No. 12 in C Minor, D. 703 "Quar...      344   
3500     3501               L'orfeo, Act 3, Sinfonia (Orchestra)      345   
3501     3502  Quintet for Horn, Violin, 2 Violas, and Cello ...      346   
3502     3503                                      Koyaanisqatsi      347   

      MediaTypeId  GenreId                                           Composer  \
0               1        1          Angus Young, Malcolm Young, Brian Johnson   
1               2        1                                               None   
2               2        1  F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...   
3               2        1  F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...   
4               2        1                         Deaffy & R.A. Smith-Diesel   
...           ...      ...                                                ...   
3498            2       24                                               None   
3499            2       24                                     Franz Schubert   
3500            2       24                                 Claudio Monteverdi   
3501            2       24                            Wolfgang Amadeus Mozart   
3502            2       10                                       Philip Glass   

      Milliseconds     Bytes  UnitPrice  
0           343719  11170334       0.99  
1           342562   5510424       0.99  
2           230619   3990994       0.99  
3           252051   4331779       0.99  
4           375418   6290521       0.99  
...            ...       ...        ...  
3498        286741   4718950       0.99  
3499        139200   2283131       0.99  
3500         66639   1189062       0.99  
3501        221331   3665114       0.99  
3502        206005   3305164       0.99  

[3503 rows x 9 columns]

### Jason Files - JSON (JavaScript Object Notation) files are commonly used for semi-structured data.

In [ ]:
import pandas as pd

# Reading data from a JSON file with specified encoding
data_from_json = pd.read_json('data.json')

# Print the DataFrame
print("DataFrame created from JSON file:")
data_from_json

DataFrame created from JSON file:


name language                id  \
0       Adeel Solangi   Sindhi  V59OF92YF627HFY0   
1       Afzal Ghaffar   Sindhi  ENTOCR13RSCLZ6KU   
2       Aamir Solangi   Sindhi  IAKPO3R4761JDRVG   
3       Abla Dilmurat   Uyghur  5ZVOEPMJUI4MB4EN   
4            Adil Eli   Uyghur  6VTI8X6LL0MMPJCC   
...               ...      ...               ...   
15835   Bhupesh Menon    Hindi  0CEPNRDV98KT3ORP   
15836    Rohini Vasav    Hindi  UEFML43TCGS04KWM   
15837    Sunil Kapoor    Hindi  VY2A0APGVHK5NAW2   
15838  Zamokuhle Zulu  isiZulu  XU7BX2F8M5PVZ1EF   
15839   Bhupesh Menon    Hindi  0CEPNRDV98KT3ORP   

                                                     bio  version  
0      Donec lobortis eleifend condimentum. Cras dict...     6.10  
1      Aliquam sollicitudin ante ligula, eget malesua...     1.88  
2      Vestibulum pharetra libero et velit gravida eu...     7.27  
3      Donec lobortis eleifend condimentum. Morbi ac ...     2.53  
4      Vivamus id faucibus velit, id posuere leo. Mor...     6.49  
...                                                  ...      ...  
15835  Maecenas tempus neque ut porttitor malesuada. ...     2.69  
15836  Ut accumsan, est vel fringilla varius, purus a...     9.30  
15837  Proin tempus eu risus nec mattis. Ut dictum, l...     8.04  
15838  Etiam congue dignissim volutpat. Phasellus tin...     8.39  
15839  Maecenas tempus neque ut porttitor malesuada. ...     2.69  

[15840 rows x 5 columns]

### HTML/Web Scraping: You can aslo Scrape data from HTML tables on webpages

In [ ]:
import pandas as pd

# Reading tables from a webpage
data_from_html = pd.read_html('https://www.w3schools.com/html/html_tables.asp')[0]  # Adjust index as needed
print("Data scraped from HTML table:")
data_from_html


Data scraped from HTML table:


Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy